/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const CartItem = IDL.Record({
  'productTitle' : IDL.Text,
  'selectedColor' : IDL.Text,
  'customizationJson' : IDL.Text,
  'productId' : IDL.Text,
  'imageUrl' : IDL.Text,
  'quantity' : IDL.Nat,
  'category' : IDL.Text,
  'price' : IDL.Float64,
  'selectedSize' : IDL.Text,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Color = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'image' : IDL.Opt(ExternalBlob),
});
export const Fabric = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'image' : IDL.Opt(ExternalBlob),
});
export const CustomizationOptions = IDL.Record({
  'sleeveStyles' : IDL.Vec(IDL.Text),
  'colorPatterns' : IDL.Vec(IDL.Text),
  'neckStyles' : IDL.Vec(IDL.Text),
  'fabricTypes' : IDL.Vec(IDL.Text),
  'workTypes' : IDL.Vec(IDL.Text),
});
export const Product = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'isDeleted' : IDL.Bool,
  'tailorId' : IDL.Text,
  'customizationOptions' : CustomizationOptions,
  'description' : IDL.Text,
  'category' : IDL.Text,
  'image' : ExternalBlob,
  'price' : IDL.Float64,
});
export const WorkType = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'image' : IDL.Opt(ExternalBlob),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Notification = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'body' : IDL.Text,
  'targetAudience' : IDL.Variant({
    'all' : IDL.Null,
    'tailors' : IDL.Null,
    'customers' : IDL.Null,
  }),
  'timestamp' : IDL.Int,
});
export const DeliveryAddress = IDL.Record({
  'area' : IDL.Text,
  'city' : IDL.Text,
  'state' : IDL.Text,
  'pinCode' : IDL.Text,
  'houseNo' : IDL.Text,
});
export const ExtendedOrder = IDL.Record({
  'id' : IDL.Text,
  'customerName' : IDL.Text,
  'status' : IDL.Text,
  'measurementsJson' : IDL.Text,
  'deliveryAddress' : DeliveryAddress,
  'isDeleted' : IDL.Bool,
  'tailorId' : IDL.Text,
  'customerAltPhone' : IDL.Text,
  'customerPhone' : IDL.Text,
  'customerPrincipal' : IDL.Text,
  'productImages' : IDL.Vec(IDL.Text),
  'customizationJson' : IDL.Text,
  'estimatedDeliveryDate' : IDL.Text,
  'orderDate' : IDL.Int,
  'orderHash' : IDL.Text,
  'paymentMode' : IDL.Text,
  'category' : IDL.Text,
  'listingTitle' : IDL.Text,
  'totalPrice' : IDL.Float64,
  'adminNotes' : IDL.Text,
});
export const TailorProfile = IDL.Record({
  'id' : IDL.Text,
  'bio' : IDL.Text,
  'portfolioJson' : IDL.Text,
  'turnaroundDays' : IDL.Nat,
  'ownerName' : IDL.Text,
  'isPremium' : IDL.Bool,
  'city' : IDL.Text,
  'contactEmail' : IDL.Text,
  'shopName' : IDL.Text,
  'specialties' : IDL.Text,
  'basePricing' : IDL.Float64,
  'profileImageUrl' : IDL.Text,
  'contactPhone' : IDL.Text,
});
export const Measurement = IDL.Record({
  'value' : IDL.Float64,
  'name' : IDL.Text,
});
export const UserProfileV2 = IDL.Record({
  'measurementsJson' : IDL.Text,
  'preferredLanguage' : IDL.Text,
  'city' : IDL.Text,
  'name' : IDL.Text,
  'role' : IDL.Text,
  'measurements' : IDL.Vec(Measurement),
  'phoneNumber' : IDL.Text,
});
export const CoinLedger = IDL.Record({
  'userId' : IDL.Text,
  'timestamp' : IDL.Int,
  'amount' : IDL.Int,
  'reason' : IDL.Text,
});
export const FontWeight = IDL.Variant({
  'normal' : IDL.Null,
  'bold' : IDL.Null,
  'light' : IDL.Null,
});
export const TextStyle = IDL.Record({
  'weight' : FontWeight,
  'font' : IDL.Text,
  'color' : IDL.Text,
  'size' : IDL.Nat,
});
export const ColorScheme = IDL.Record({
  'accent' : IDL.Text,
  'background' : IDL.Text,
  'text' : IDL.Text,
  'secondary' : IDL.Text,
  'primary' : IDL.Text,
});
export const ButtonStyle = IDL.Record({
  'borderRadius' : IDL.Nat,
  'background' : IDL.Text,
  'text' : TextStyle,
  'padding' : IDL.Text,
});
export const AppStyle = IDL.Record({
  'fonts' : IDL.Record({ 'body' : TextStyle, 'heading' : TextStyle }),
  'backgroundImage' : IDL.Opt(ExternalBlob),
  'colors' : ColorScheme,
  'buttons' : IDL.Record({
    'secondary' : ButtonStyle,
    'primary' : ButtonStyle,
  }),
});
export const Promotion = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'active' : IDL.Bool,
  'discountValue' : IDL.Nat,
  'validFrom' : IDL.Int,
  'discountType' : IDL.Variant({ 'flat' : IDL.Nat, 'percentage' : IDL.Nat }),
  'description' : IDL.Text,
  'applicableCategories' : IDL.Vec(IDL.Text),
  'validUntil' : IDL.Int,
});
export const City = IDL.Record({ 'id' : IDL.Text, 'name' : IDL.Text });
export const PlatformConfig = IDL.Record({
  'promotions' : IDL.Vec(Promotion),
  'fabrics' : IDL.Vec(Fabric),
  'banners' : IDL.Vec(ExternalBlob),
  'cities' : IDL.Vec(City),
  'colors' : IDL.Vec(Color),
  'products' : IDL.Vec(Product),
  'workTypes' : IDL.Vec(WorkType),
});
export const ApprovalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const UserApprovalInfo = IDL.Record({
  'status' : ApprovalStatus,
  'principal' : IDL.Principal,
});
export const MeasurementInput = IDL.Record({
  'value' : IDL.Float64,
  'name' : IDL.Text,
});
export const UserProfileInput = IDL.Record({
  'measurementsJson' : IDL.Text,
  'preferredLanguage' : IDL.Text,
  'city' : IDL.Text,
  'name' : IDL.Text,
  'role' : IDL.Text,
  'measurements' : IDL.Vec(MeasurementInput),
  'phoneNumber' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addToCart' : IDL.Func([CartItem], [], []),
  'adminAddColor' : IDL.Func([Color], [], []),
  'adminAddFabric' : IDL.Func([Fabric], [], []),
  'adminAddProduct' : IDL.Func([Product], [], []),
  'adminAddWorkType' : IDL.Func([WorkType], [], []),
  'adminDeleteColor' : IDL.Func([IDL.Text], [], []),
  'adminDeleteFabric' : IDL.Func([IDL.Text], [], []),
  'adminDeleteProduct' : IDL.Func([IDL.Text], [], []),
  'adminDeleteWorkType' : IDL.Func([IDL.Text], [], []),
  'adminUpdateProduct' : IDL.Func([Product], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'cancelOrder' : IDL.Func([IDL.Text], [], []),
  'clearCart' : IDL.Func([], [], []),
  'createNotification' : IDL.Func([Notification], [], []),
  'getAllExtendedOrders' : IDL.Func([], [IDL.Vec(ExtendedOrder)], ['query']),
  'getAllTailorProfiles' : IDL.Func([], [IDL.Vec(TailorProfile)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfileV2)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCart' : IDL.Func([], [IDL.Vec(CartItem)], ['query']),
  'getCoinHistory' : IDL.Func([], [IDL.Vec(CoinLedger)], ['query']),
  'getDefaultAppStyle' : IDL.Func([], [AppStyle], ['query']),
  'getLastUpdateTimestamp' : IDL.Func([], [IDL.Int], ['query']),
  'getMyExtendedOrders' : IDL.Func([], [IDL.Vec(ExtendedOrder)], ['query']),
  'getNotifications' : IDL.Func([IDL.Int], [IDL.Vec(Notification)], ['query']),
  'getOrderById' : IDL.Func([IDL.Text], [IDL.Opt(ExtendedOrder)], ['query']),
  'getPlatformConfig' : IDL.Func([], [IDL.Opt(PlatformConfig)], ['query']),
  'getTailorProfile' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(TailorProfile)],
      ['query'],
    ),
  'getUserCoinBalance' : IDL.Func([], [IDL.Int], ['query']),
  'getUserProfile' : IDL.Func([], [IDL.Opt(UserProfileV2)], ['query']),
  'getUserProfileByPrincipal' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfileV2)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
  'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
  'placeExtendedOrder' : IDL.Func([ExtendedOrder], [IDL.Text], []),
  'removeFromCart' : IDL.Func([IDL.Text], [], []),
  'requestApproval' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfileInput], [], []),
  'saveTailorProfile' : IDL.Func([TailorProfile], [], []),
  'saveUserProfile' : IDL.Func([UserProfileInput], [], []),
  'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
  'updateExtendedOrderStatus' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updatePlatformConfig' : IDL.Func([PlatformConfig], [], []),
  'updateUserRole' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const CartItem = IDL.Record({
    'productTitle' : IDL.Text,
    'selectedColor' : IDL.Text,
    'customizationJson' : IDL.Text,
    'productId' : IDL.Text,
    'imageUrl' : IDL.Text,
    'quantity' : IDL.Nat,
    'category' : IDL.Text,
    'price' : IDL.Float64,
    'selectedSize' : IDL.Text,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Color = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'image' : IDL.Opt(ExternalBlob),
  });
  const Fabric = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'image' : IDL.Opt(ExternalBlob),
  });
  const CustomizationOptions = IDL.Record({
    'sleeveStyles' : IDL.Vec(IDL.Text),
    'colorPatterns' : IDL.Vec(IDL.Text),
    'neckStyles' : IDL.Vec(IDL.Text),
    'fabricTypes' : IDL.Vec(IDL.Text),
    'workTypes' : IDL.Vec(IDL.Text),
  });
  const Product = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'isDeleted' : IDL.Bool,
    'tailorId' : IDL.Text,
    'customizationOptions' : CustomizationOptions,
    'description' : IDL.Text,
    'category' : IDL.Text,
    'image' : ExternalBlob,
    'price' : IDL.Float64,
  });
  const WorkType = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'image' : IDL.Opt(ExternalBlob),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Notification = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'body' : IDL.Text,
    'targetAudience' : IDL.Variant({
      'all' : IDL.Null,
      'tailors' : IDL.Null,
      'customers' : IDL.Null,
    }),
    'timestamp' : IDL.Int,
  });
  const DeliveryAddress = IDL.Record({
    'area' : IDL.Text,
    'city' : IDL.Text,
    'state' : IDL.Text,
    'pinCode' : IDL.Text,
    'houseNo' : IDL.Text,
  });
  const ExtendedOrder = IDL.Record({
    'id' : IDL.Text,
    'customerName' : IDL.Text,
    'status' : IDL.Text,
    'measurementsJson' : IDL.Text,
    'deliveryAddress' : DeliveryAddress,
    'isDeleted' : IDL.Bool,
    'tailorId' : IDL.Text,
    'customerAltPhone' : IDL.Text,
    'customerPhone' : IDL.Text,
    'customerPrincipal' : IDL.Text,
    'productImages' : IDL.Vec(IDL.Text),
    'customizationJson' : IDL.Text,
    'estimatedDeliveryDate' : IDL.Text,
    'orderDate' : IDL.Int,
    'orderHash' : IDL.Text,
    'paymentMode' : IDL.Text,
    'category' : IDL.Text,
    'listingTitle' : IDL.Text,
    'totalPrice' : IDL.Float64,
    'adminNotes' : IDL.Text,
  });
  const TailorProfile = IDL.Record({
    'id' : IDL.Text,
    'bio' : IDL.Text,
    'portfolioJson' : IDL.Text,
    'turnaroundDays' : IDL.Nat,
    'ownerName' : IDL.Text,
    'isPremium' : IDL.Bool,
    'city' : IDL.Text,
    'contactEmail' : IDL.Text,
    'shopName' : IDL.Text,
    'specialties' : IDL.Text,
    'basePricing' : IDL.Float64,
    'profileImageUrl' : IDL.Text,
    'contactPhone' : IDL.Text,
  });
  const Measurement = IDL.Record({ 'value' : IDL.Float64, 'name' : IDL.Text });
  const UserProfileV2 = IDL.Record({
    'measurementsJson' : IDL.Text,
    'preferredLanguage' : IDL.Text,
    'city' : IDL.Text,
    'name' : IDL.Text,
    'role' : IDL.Text,
    'measurements' : IDL.Vec(Measurement),
    'phoneNumber' : IDL.Text,
  });
  const CoinLedger = IDL.Record({
    'userId' : IDL.Text,
    'timestamp' : IDL.Int,
    'amount' : IDL.Int,
    'reason' : IDL.Text,
  });
  const FontWeight = IDL.Variant({
    'normal' : IDL.Null,
    'bold' : IDL.Null,
    'light' : IDL.Null,
  });
  const TextStyle = IDL.Record({
    'weight' : FontWeight,
    'font' : IDL.Text,
    'color' : IDL.Text,
    'size' : IDL.Nat,
  });
  const ColorScheme = IDL.Record({
    'accent' : IDL.Text,
    'background' : IDL.Text,
    'text' : IDL.Text,
    'secondary' : IDL.Text,
    'primary' : IDL.Text,
  });
  const ButtonStyle = IDL.Record({
    'borderRadius' : IDL.Nat,
    'background' : IDL.Text,
    'text' : TextStyle,
    'padding' : IDL.Text,
  });
  const AppStyle = IDL.Record({
    'fonts' : IDL.Record({ 'body' : TextStyle, 'heading' : TextStyle }),
    'backgroundImage' : IDL.Opt(ExternalBlob),
    'colors' : ColorScheme,
    'buttons' : IDL.Record({
      'secondary' : ButtonStyle,
      'primary' : ButtonStyle,
    }),
  });
  const Promotion = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'active' : IDL.Bool,
    'discountValue' : IDL.Nat,
    'validFrom' : IDL.Int,
    'discountType' : IDL.Variant({ 'flat' : IDL.Nat, 'percentage' : IDL.Nat }),
    'description' : IDL.Text,
    'applicableCategories' : IDL.Vec(IDL.Text),
    'validUntil' : IDL.Int,
  });
  const City = IDL.Record({ 'id' : IDL.Text, 'name' : IDL.Text });
  const PlatformConfig = IDL.Record({
    'promotions' : IDL.Vec(Promotion),
    'fabrics' : IDL.Vec(Fabric),
    'banners' : IDL.Vec(ExternalBlob),
    'cities' : IDL.Vec(City),
    'colors' : IDL.Vec(Color),
    'products' : IDL.Vec(Product),
    'workTypes' : IDL.Vec(WorkType),
  });
  const ApprovalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const UserApprovalInfo = IDL.Record({
    'status' : ApprovalStatus,
    'principal' : IDL.Principal,
  });
  const MeasurementInput = IDL.Record({
    'value' : IDL.Float64,
    'name' : IDL.Text,
  });
  const UserProfileInput = IDL.Record({
    'measurementsJson' : IDL.Text,
    'preferredLanguage' : IDL.Text,
    'city' : IDL.Text,
    'name' : IDL.Text,
    'role' : IDL.Text,
    'measurements' : IDL.Vec(MeasurementInput),
    'phoneNumber' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addToCart' : IDL.Func([CartItem], [], []),
    'adminAddColor' : IDL.Func([Color], [], []),
    'adminAddFabric' : IDL.Func([Fabric], [], []),
    'adminAddProduct' : IDL.Func([Product], [], []),
    'adminAddWorkType' : IDL.Func([WorkType], [], []),
    'adminDeleteColor' : IDL.Func([IDL.Text], [], []),
    'adminDeleteFabric' : IDL.Func([IDL.Text], [], []),
    'adminDeleteProduct' : IDL.Func([IDL.Text], [], []),
    'adminDeleteWorkType' : IDL.Func([IDL.Text], [], []),
    'adminUpdateProduct' : IDL.Func([Product], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'cancelOrder' : IDL.Func([IDL.Text], [], []),
    'clearCart' : IDL.Func([], [], []),
    'createNotification' : IDL.Func([Notification], [], []),
    'getAllExtendedOrders' : IDL.Func([], [IDL.Vec(ExtendedOrder)], ['query']),
    'getAllTailorProfiles' : IDL.Func([], [IDL.Vec(TailorProfile)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfileV2)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCart' : IDL.Func([], [IDL.Vec(CartItem)], ['query']),
    'getCoinHistory' : IDL.Func([], [IDL.Vec(CoinLedger)], ['query']),
    'getDefaultAppStyle' : IDL.Func([], [AppStyle], ['query']),
    'getLastUpdateTimestamp' : IDL.Func([], [IDL.Int], ['query']),
    'getMyExtendedOrders' : IDL.Func([], [IDL.Vec(ExtendedOrder)], ['query']),
    'getNotifications' : IDL.Func(
        [IDL.Int],
        [IDL.Vec(Notification)],
        ['query'],
      ),
    'getOrderById' : IDL.Func([IDL.Text], [IDL.Opt(ExtendedOrder)], ['query']),
    'getPlatformConfig' : IDL.Func([], [IDL.Opt(PlatformConfig)], ['query']),
    'getTailorProfile' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(TailorProfile)],
        ['query'],
      ),
    'getUserCoinBalance' : IDL.Func([], [IDL.Int], ['query']),
    'getUserProfile' : IDL.Func([], [IDL.Opt(UserProfileV2)], ['query']),
    'getUserProfileByPrincipal' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfileV2)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
    'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
    'placeExtendedOrder' : IDL.Func([ExtendedOrder], [IDL.Text], []),
    'removeFromCart' : IDL.Func([IDL.Text], [], []),
    'requestApproval' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfileInput], [], []),
    'saveTailorProfile' : IDL.Func([TailorProfile], [], []),
    'saveUserProfile' : IDL.Func([UserProfileInput], [], []),
    'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
    'updateExtendedOrderStatus' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updatePlatformConfig' : IDL.Func([PlatformConfig], [], []),
    'updateUserRole' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };