 

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Notification = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'body' : IDL.Text,
  'targetAudience' : IDL.Variant({
    'all' : IDL.Null,
    'tailors' : IDL.Null,
    'customers' : IDL.Null,
  }),
  'timestamp' : IDL.Int,
});
export const FontWeight = IDL.Variant({
  'normal' : IDL.Null,
  'bold' : IDL.Null,
  'light' : IDL.Null,
});
export const TextStyle = IDL.Record({
  'weight' : FontWeight,
  'font' : IDL.Text,
  'color' : IDL.Text,
  'size' : IDL.Nat,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const ColorScheme = IDL.Record({
  'accent' : IDL.Text,
  'background' : IDL.Text,
  'text' : IDL.Text,
  'secondary' : IDL.Text,
  'primary' : IDL.Text,
});
export const ButtonStyle = IDL.Record({
  'borderRadius' : IDL.Nat,
  'background' : IDL.Text,
  'text' : TextStyle,
  'padding' : IDL.Text,
});
export const AppStyle = IDL.Record({
  'fonts' : IDL.Record({ 'body' : TextStyle, 'heading' : TextStyle }),
  'backgroundImage' : IDL.Opt(ExternalBlob),
  'colors' : ColorScheme,
  'buttons' : IDL.Record({
    'secondary' : ButtonStyle,
    'primary' : ButtonStyle,
  }),
});
export const Promotion = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'active' : IDL.Bool,
  'discountValue' : IDL.Nat,
  'validFrom' : IDL.Int,
  'discountType' : IDL.Variant({ 'flat' : IDL.Nat, 'percentage' : IDL.Nat }),
  'description' : IDL.Text,
  'applicableCategories' : IDL.Vec(IDL.Text),
  'validUntil' : IDL.Int,
});
export const Fabric = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'image' : IDL.Opt(ExternalBlob),
});
export const City = IDL.Record({ 'id' : IDL.Text, 'name' : IDL.Text });
export const Color = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'image' : IDL.Opt(ExternalBlob),
});
export const CustomizationOptions = IDL.Record({
  'sleeveStyles' : IDL.Vec(IDL.Text),
  'colorPatterns' : IDL.Vec(IDL.Text),
  'neckStyles' : IDL.Vec(IDL.Text),
  'fabricTypes' : IDL.Vec(IDL.Text),
  'workTypes' : IDL.Vec(IDL.Text),
});
export const Product = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'tailorId' : IDL.Text,
  'customizationOptions' : CustomizationOptions,
  'description' : IDL.Text,
  'category' : IDL.Text,
  'image' : ExternalBlob,
  'price' : IDL.Float64,
});
export const WorkType = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'image' : IDL.Opt(ExternalBlob),
});
export const PlatformConfig = IDL.Record({
  'promotions' : IDL.Vec(Promotion),
  'fabrics' : IDL.Vec(Fabric),
  'banners' : IDL.Vec(ExternalBlob),
  'cities' : IDL.Vec(City),
  'colors' : IDL.Vec(Color),
  'products' : IDL.Vec(Product),
  'workTypes' : IDL.Vec(WorkType),
});
export const Measurement = IDL.Record({
  'value' : IDL.Float64,
  'name' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'preferredLanguage' : IDL.Text,
  'city' : IDL.Text,
  'name' : IDL.Text,
  'measurements' : IDL.Vec(Measurement),
  'phoneNumber' : IDL.Text,
});
export const ApprovalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const UserApprovalInfo = IDL.Record({
  'status' : ApprovalStatus,
  'principal' : IDL.Principal,
});
export const MeasurementInput = IDL.Record({
  'value' : IDL.Float64,
  'name' : IDL.Text,
});
export const UserProfileInput = IDL.Record({
  'preferredLanguage' : IDL.Text,
  'city' : IDL.Text,
  'name' : IDL.Text,
  'measurements' : IDL.Vec(MeasurementInput),
  'phoneNumber' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createNotification' : IDL.Func([Notification], [], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDefaultAppStyle' : IDL.Func([], [AppStyle], ['query']),
  'getNotifications' : IDL.Func([IDL.Int], [IDL.Vec(Notification)], ['query']),
  'getPlatformConfig' : IDL.Func([], [IDL.Opt(PlatformConfig)], ['query']),
  'getUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getUserProfileByPrincipal' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
  'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
  'requestApproval' : IDL.Func([], [], []),
  'saveUserProfile' : IDL.Func([UserProfileInput], [], []),
  'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
  'updatePlatformConfig' : IDL.Func([PlatformConfig], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Notification = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'body' : IDL.Text,
    'targetAudience' : IDL.Variant({
      'all' : IDL.Null,
      'tailors' : IDL.Null,
      'customers' : IDL.Null,
    }),
    'timestamp' : IDL.Int,
  });
  const FontWeight = IDL.Variant({
    'normal' : IDL.Null,
    'bold' : IDL.Null,
    'light' : IDL.Null,
  });
  const TextStyle = IDL.Record({
    'weight' : FontWeight,
    'font' : IDL.Text,
    'color' : IDL.Text,
    'size' : IDL.Nat,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const ColorScheme = IDL.Record({
    'accent' : IDL.Text,
    'background' : IDL.Text,
    'text' : IDL.Text,
    'secondary' : IDL.Text,
    'primary' : IDL.Text,
  });
  const ButtonStyle = IDL.Record({
    'borderRadius' : IDL.Nat,
    'background' : IDL.Text,
    'text' : TextStyle,
    'padding' : IDL.Text,
  });
  const AppStyle = IDL.Record({
    'fonts' : IDL.Record({ 'body' : TextStyle, 'heading' : TextStyle }),
    'backgroundImage' : IDL.Opt(ExternalBlob),
    'colors' : ColorScheme,
    'buttons' : IDL.Record({
      'secondary' : ButtonStyle,
      'primary' : ButtonStyle,
    }),
  });
  const Promotion = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'active' : IDL.Bool,
    'discountValue' : IDL.Nat,
    'validFrom' : IDL.Int,
    'discountType' : IDL.Variant({ 'flat' : IDL.Nat, 'percentage' : IDL.Nat }),
    'description' : IDL.Text,
    'applicableCategories' : IDL.Vec(IDL.Text),
    'validUntil' : IDL.Int,
  });
  const Fabric = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'image' : IDL.Opt(ExternalBlob),
  });
  const City = IDL.Record({ 'id' : IDL.Text, 'name' : IDL.Text });
  const Color = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'image' : IDL.Opt(ExternalBlob),
  });
  const CustomizationOptions = IDL.Record({
    'sleeveStyles' : IDL.Vec(IDL.Text),
    'colorPatterns' : IDL.Vec(IDL.Text),
    'neckStyles' : IDL.Vec(IDL.Text),
    'fabricTypes' : IDL.Vec(IDL.Text),
    'workTypes' : IDL.Vec(IDL.Text),
  });
  const Product = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'tailorId' : IDL.Text,
    'customizationOptions' : CustomizationOptions,
    'description' : IDL.Text,
    'category' : IDL.Text,
    'image' : ExternalBlob,
    'price' : IDL.Float64,
  });
  const WorkType = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'image' : IDL.Opt(ExternalBlob),
  });
  const PlatformConfig = IDL.Record({
    'promotions' : IDL.Vec(Promotion),
    'fabrics' : IDL.Vec(Fabric),
    'banners' : IDL.Vec(ExternalBlob),
    'cities' : IDL.Vec(City),
    'colors' : IDL.Vec(Color),
    'products' : IDL.Vec(Product),
    'workTypes' : IDL.Vec(WorkType),
  });
  const Measurement = IDL.Record({ 'value' : IDL.Float64, 'name' : IDL.Text });
  const UserProfile = IDL.Record({
    'preferredLanguage' : IDL.Text,
    'city' : IDL.Text,
    'name' : IDL.Text,
    'measurements' : IDL.Vec(Measurement),
    'phoneNumber' : IDL.Text,
  });
  const ApprovalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const UserApprovalInfo = IDL.Record({
    'status' : ApprovalStatus,
    'principal' : IDL.Principal,
  });
  const MeasurementInput = IDL.Record({
    'value' : IDL.Float64,
    'name' : IDL.Text,
  });
  const UserProfileInput = IDL.Record({
    'preferredLanguage' : IDL.Text,
    'city' : IDL.Text,
    'name' : IDL.Text,
    'measurements' : IDL.Vec(MeasurementInput),
    'phoneNumber' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createNotification' : IDL.Func([Notification], [], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDefaultAppStyle' : IDL.Func([], [AppStyle], ['query']),
    'getNotifications' : IDL.Func(
        [IDL.Int],
        [IDL.Vec(Notification)],
        ['query'],
      ),
    'getPlatformConfig' : IDL.Func([], [IDL.Opt(PlatformConfig)], ['query']),
    'getUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getUserProfileByPrincipal' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
    'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
    'requestApproval' : IDL.Func([], [], []),
    'saveUserProfile' : IDL.Func([UserProfileInput], [], []),
    'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
    'updatePlatformConfig' : IDL.Func([PlatformConfig], [], []),
  });
};

export const init = ({ IDL }) => { return []; };