/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AppStyle {
  'fonts' : { 'body' : TextStyle, 'heading' : TextStyle },
  'backgroundImage' : [] | [ExternalBlob],
  'colors' : ColorScheme,
  'buttons' : { 'secondary' : ButtonStyle, 'primary' : ButtonStyle },
}
export type ApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface ButtonStyle {
  'borderRadius' : bigint,
  'background' : string,
  'text' : TextStyle,
  'padding' : string,
}
export interface City { 'id' : string, 'name' : string }
export interface Color {
  'id' : string,
  'name' : string,
  'image' : [] | [ExternalBlob],
}
export interface ColorScheme {
  'accent' : string,
  'background' : string,
  'text' : string,
  'secondary' : string,
  'primary' : string,
}
export interface CustomizationOptions {
  'sleeveStyles' : Array<string>,
  'colorPatterns' : Array<string>,
  'neckStyles' : Array<string>,
  'fabricTypes' : Array<string>,
  'workTypes' : Array<string>,
}
export type ExternalBlob = Uint8Array;
export interface Fabric {
  'id' : string,
  'name' : string,
  'image' : [] | [ExternalBlob],
}
export type FontWeight = { 'normal' : null } |
  { 'bold' : null } |
  { 'light' : null };
export interface Measurement { 'value' : number, 'name' : string }
export interface MeasurementInput { 'value' : number, 'name' : string }
export interface Notification {
  'id' : string,
  'title' : string,
  'body' : string,
  'targetAudience' : { 'all' : null } |
    { 'tailors' : null } |
    { 'customers' : null },
  'timestamp' : bigint,
}
export interface Order {
  'id' : string,
  'status' : string,
  'measurementsJson' : string,
  'tailorId' : string,
  'customerPrincipal' : string,
  'customizationJson' : string,
  'estimatedDeliveryDate' : string,
  'orderDate' : bigint,
  'category' : string,
  'listingTitle' : string,
  'totalPrice' : number,
  'adminNotes' : string,
}
export interface PlatformConfig {
  'promotions' : Array<Promotion>,
  'fabrics' : Array<Fabric>,
  'banners' : Array<ExternalBlob>,
  'cities' : Array<City>,
  'colors' : Array<Color>,
  'products' : Array<Product>,
  'workTypes' : Array<WorkType>,
}
export interface Product {
  'id' : string,
  'title' : string,
  'tailorId' : string,
  'customizationOptions' : CustomizationOptions,
  'description' : string,
  'category' : string,
  'image' : ExternalBlob,
  'price' : number,
}
export interface Promotion {
  'id' : string,
  'title' : string,
  'active' : boolean,
  'discountValue' : bigint,
  'validFrom' : bigint,
  'discountType' : { 'flat' : bigint } |
    { 'percentage' : bigint },
  'description' : string,
  'applicableCategories' : Array<string>,
  'validUntil' : bigint,
}
export interface TailorProfile {
  'id' : string,
  'bio' : string,
  'portfolioJson' : string,
  'turnaroundDays' : bigint,
  'ownerName' : string,
  'isPremium' : boolean,
  'city' : string,
  'contactEmail' : string,
  'shopName' : string,
  'specialties' : string,
  'basePricing' : number,
  'profileImageUrl' : string,
  'contactPhone' : string,
}
export interface TextStyle {
  'weight' : FontWeight,
  'font' : string,
  'color' : string,
  'size' : bigint,
}
export interface UserApprovalInfo {
  'status' : ApprovalStatus,
  'principal' : Principal,
}
export interface UserProfileInput {
  'measurementsJson' : string,
  'preferredLanguage' : string,
  'city' : string,
  'name' : string,
  'role' : string,
  'measurements' : Array<MeasurementInput>,
  'phoneNumber' : string,
}
export interface UserProfileV2 {
  'measurementsJson' : string,
  'preferredLanguage' : string,
  'city' : string,
  'name' : string,
  'role' : string,
  'measurements' : Array<Measurement>,
  'phoneNumber' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WorkType {
  'id' : string,
  'name' : string,
  'image' : [] | [ExternalBlob],
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createNotification' : ActorMethod<[Notification], undefined>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getAllTailorProfiles' : ActorMethod<[], Array<TailorProfile>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfileV2]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDefaultAppStyle' : ActorMethod<[], AppStyle>,
  'getMyOrders' : ActorMethod<[], Array<Order>>,
  'getNotifications' : ActorMethod<[bigint], Array<Notification>>,
  'getPlatformConfig' : ActorMethod<[], [] | [PlatformConfig]>,
  'getTailorProfile' : ActorMethod<[string], [] | [TailorProfile]>,
  'getUserProfile' : ActorMethod<[], [] | [UserProfileV2]>,
  'getUserProfileByPrincipal' : ActorMethod<[Principal], [] | [UserProfileV2]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerApproved' : ActorMethod<[], boolean>,
  'listApprovals' : ActorMethod<[], Array<UserApprovalInfo>>,
  'placeOrder' : ActorMethod<[Order], string>,
  'requestApproval' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfileInput], undefined>,
  'saveTailorProfile' : ActorMethod<[TailorProfile], undefined>,
  'saveUserProfile' : ActorMethod<[UserProfileInput], undefined>,
  'setApproval' : ActorMethod<[Principal, ApprovalStatus], undefined>,
  'setOrderDeliveryDate' : ActorMethod<[string, string], undefined>,
  'updateOrderStatus' : ActorMethod<[string, string, string], undefined>,
  'updatePlatformConfig' : ActorMethod<[PlatformConfig], undefined>,
  'updateUserRole' : ActorMethod<[string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];