/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Product {
    id: string;
    title: string;
    isDeleted: boolean;
    tailorId: string;
    customizationOptions: CustomizationOptions;
    description: string;
    category: string;
    image: ExternalBlob;
    price: number;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface CoinLedger {
    userId: string;
    timestamp: bigint;
    amount: bigint;
    reason: string;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface TailorProfile {
    id: string;
    bio: string;
    portfolioJson: string;
    turnaroundDays: bigint;
    ownerName: string;
    isPremium: boolean;
    city: string;
    contactEmail: string;
    shopName: string;
    specialties: string;
    basePricing: number;
    profileImageUrl: string;
    contactPhone: string;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface PlatformConfig {
    promotions: Array<Promotion>;
    fabrics: Array<Fabric>;
    banners: Array<ExternalBlob>;
    cities: Array<City>;
    colors: Array<Color>;
    products: Array<Product>;
    workTypes: Array<WorkType>;
}
export interface City {
    id: string;
    name: string;
}
export interface ColorScheme {
    accent: string;
    background: string;
    text: string;
    secondary: string;
    primary: string;
}
export interface Color {
    id: string;
    name: string;
    image?: ExternalBlob;
}
export interface MeasurementInput {
    value: number;
    name: string;
}
export interface DeliveryAddress {
    area: string;
    city: string;
    state: string;
    pinCode: string;
    houseNo: string;
}
export interface Promotion {
    id: string;
    title: string;
    active: boolean;
    discountValue: bigint;
    validFrom: bigint;
    discountType: {
        __kind__: "flat";
        flat: bigint;
    } | {
        __kind__: "percentage";
        percentage: bigint;
    };
    description: string;
    applicableCategories: Array<string>;
    validUntil: bigint;
}
export interface UserProfileV2 {
    measurementsJson: string;
    preferredLanguage: string;
    city: string;
    name: string;
    role: string;
    measurements: Array<Measurement>;
    phoneNumber: string;
}
export interface TextStyle {
    weight: FontWeight;
    font: string;
    color: string;
    size: bigint;
}
export interface ButtonStyle {
    borderRadius: bigint;
    background: string;
    text: TextStyle;
    padding: string;
}
export interface UserApprovalInfo {
    status: ApprovalStatus;
    principal: Principal;
}
export interface WorkType {
    id: string;
    name: string;
    image?: ExternalBlob;
}
export interface ExtendedOrder {
    id: string;
    customerName: string;
    status: string;
    measurementsJson: string;
    deliveryAddress: DeliveryAddress;
    isDeleted: boolean;
    tailorId: string;
    customerAltPhone: string;
    customerPhone: string;
    customerPrincipal: string;
    productImages: Array<string>;
    customizationJson: string;
    estimatedDeliveryDate: string;
    orderDate: bigint;
    orderHash: string;
    paymentMode: string;
    category: string;
    listingTitle: string;
    totalPrice: number;
    adminNotes: string;
}
export interface Measurement {
    value: number;
    name: string;
}
export interface Notification {
    id: string;
    title: string;
    body: string;
    targetAudience: Variant_all_tailors_customers;
    timestamp: bigint;
}
export interface CartItem {
    productTitle: string;
    selectedColor: string;
    customizationJson: string;
    productId: string;
    imageUrl: string;
    quantity: bigint;
    category: string;
    price: number;
    selectedSize: string;
}
export interface AppStyle {
    fonts: {
        body: TextStyle;
        heading: TextStyle;
    };
    backgroundImage?: ExternalBlob;
    colors: ColorScheme;
    buttons: {
        secondary: ButtonStyle;
        primary: ButtonStyle;
    };
}
export interface Fabric {
    id: string;
    name: string;
    image?: ExternalBlob;
}
export interface CustomizationOptions {
    sleeveStyles: Array<string>;
    colorPatterns: Array<string>;
    neckStyles: Array<string>;
    fabricTypes: Array<string>;
    workTypes: Array<string>;
}
export interface UserProfileInput {
    measurementsJson: string;
    preferredLanguage: string;
    city: string;
    name: string;
    role: string;
    measurements: Array<MeasurementInput>;
    phoneNumber: string;
}
export enum ApprovalStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum FontWeight {
    normal = "normal",
    bold = "bold",
    light = "light"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_all_tailors_customers {
    all = "all",
    tailors = "tailors",
    customers = "customers"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addToCart(item: CartItem): Promise<void>;
    adminAddColor(color: Color): Promise<void>;
    adminAddFabric(fabric: Fabric): Promise<void>;
    adminAddProduct(product: Product): Promise<void>;
    adminAddWorkType(workType: WorkType): Promise<void>;
    adminDeleteColor(colorId: string): Promise<void>;
    adminDeleteFabric(fabricId: string): Promise<void>;
    adminDeleteProduct(productId: string): Promise<void>;
    adminDeleteWorkType(workTypeId: string): Promise<void>;
    adminUpdateProduct(product: Product): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    cancelOrder(orderId: string): Promise<void>;
    clearCart(): Promise<void>;
    createNotification(notification: Notification): Promise<void>;
    getAllExtendedOrders(): Promise<Array<ExtendedOrder>>;
    getAllTailorProfiles(): Promise<Array<TailorProfile>>;
    getCallerUserProfile(): Promise<UserProfileV2 | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCart(): Promise<Array<CartItem>>;
    getCoinHistory(): Promise<Array<CoinLedger>>;
    getDefaultAppStyle(): Promise<AppStyle>;
    getLastUpdateTimestamp(): Promise<bigint>;
    getMyExtendedOrders(): Promise<Array<ExtendedOrder>>;
    getNotifications(sinceTimestamp: bigint): Promise<Array<Notification>>;
    getOrderById(orderId: string): Promise<ExtendedOrder | null>;
    getPlatformConfig(): Promise<PlatformConfig | null>;
    getTailorProfile(tailorId: string): Promise<TailorProfile | null>;
    getUserCoinBalance(): Promise<bigint>;
    getUserProfile(): Promise<UserProfileV2 | null>;
    getUserProfileByPrincipal(user: Principal): Promise<UserProfileV2 | null>;
    isCallerAdmin(): Promise<boolean>;
    isCallerApproved(): Promise<boolean>;
    listApprovals(): Promise<Array<UserApprovalInfo>>;
    placeExtendedOrder(order: ExtendedOrder): Promise<string>;
    removeFromCart(productId: string): Promise<void>;
    requestApproval(): Promise<void>;
    saveCallerUserProfile(profileInput: UserProfileInput): Promise<void>;
    saveTailorProfile(profile: TailorProfile): Promise<void>;
    saveUserProfile(profileInput: UserProfileInput): Promise<void>;
    setApproval(user: Principal, status: ApprovalStatus): Promise<void>;
    updateExtendedOrderStatus(orderId: string, newStatus: string, adminNote: string): Promise<void>;
    updatePlatformConfig(config: PlatformConfig): Promise<void>;
    updateUserRole(role: string): Promise<void>;
}
import type { AppStyle as _AppStyle, ApprovalStatus as _ApprovalStatus, ButtonStyle as _ButtonStyle, City as _City, Color as _Color, ColorScheme as _ColorScheme, CustomizationOptions as _CustomizationOptions, ExtendedOrder as _ExtendedOrder, ExternalBlob as _ExternalBlob, Fabric as _Fabric, FontWeight as _FontWeight, Notification as _Notification, PlatformConfig as _PlatformConfig, Product as _Product, Promotion as _Promotion, TailorProfile as _TailorProfile, TextStyle as _TextStyle, UserApprovalInfo as _UserApprovalInfo, UserProfileV2 as _UserProfileV2, UserRole as _UserRole, WorkType as _WorkType, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addToCart(arg0: CartItem): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addToCart(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addToCart(arg0);
            return result;
        }
    }
    async adminAddColor(arg0: Color): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminAddColor(await to_candid_Color_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminAddColor(await to_candid_Color_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async adminAddFabric(arg0: Fabric): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminAddFabric(await to_candid_Fabric_n11(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminAddFabric(await to_candid_Fabric_n11(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async adminAddProduct(arg0: Product): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminAddProduct(await to_candid_Product_n12(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminAddProduct(await to_candid_Product_n12(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async adminAddWorkType(arg0: WorkType): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminAddWorkType(await to_candid_WorkType_n14(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminAddWorkType(await to_candid_WorkType_n14(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async adminDeleteColor(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminDeleteColor(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminDeleteColor(arg0);
            return result;
        }
    }
    async adminDeleteFabric(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminDeleteFabric(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminDeleteFabric(arg0);
            return result;
        }
    }
    async adminDeleteProduct(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminDeleteProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminDeleteProduct(arg0);
            return result;
        }
    }
    async adminDeleteWorkType(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminDeleteWorkType(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminDeleteWorkType(arg0);
            return result;
        }
    }
    async adminUpdateProduct(arg0: Product): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminUpdateProduct(await to_candid_Product_n12(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminUpdateProduct(await to_candid_Product_n12(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n15(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n15(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async cancelOrder(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelOrder(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelOrder(arg0);
            return result;
        }
    }
    async clearCart(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearCart();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearCart();
            return result;
        }
    }
    async createNotification(arg0: Notification): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createNotification(to_candid_Notification_n17(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createNotification(to_candid_Notification_n17(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getAllExtendedOrders(): Promise<Array<ExtendedOrder>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllExtendedOrders();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllExtendedOrders();
            return result;
        }
    }
    async getAllTailorProfiles(): Promise<Array<TailorProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTailorProfiles();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTailorProfiles();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfileV2 | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCart(): Promise<Array<CartItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCart();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCart();
            return result;
        }
    }
    async getCoinHistory(): Promise<Array<CoinLedger>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCoinHistory();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCoinHistory();
            return result;
        }
    }
    async getDefaultAppStyle(): Promise<AppStyle> {
        if (this.processError) {
            try {
                const result = await this.actor.getDefaultAppStyle();
                return from_candid_AppStyle_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDefaultAppStyle();
            return from_candid_AppStyle_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLastUpdateTimestamp(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getLastUpdateTimestamp();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLastUpdateTimestamp();
            return result;
        }
    }
    async getMyExtendedOrders(): Promise<Array<ExtendedOrder>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyExtendedOrders();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyExtendedOrders();
            return result;
        }
    }
    async getNotifications(arg0: bigint): Promise<Array<Notification>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNotifications(arg0);
                return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNotifications(arg0);
            return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrderById(arg0: string): Promise<ExtendedOrder | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrderById(arg0);
                return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrderById(arg0);
            return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPlatformConfig(): Promise<PlatformConfig | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlatformConfig();
                return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlatformConfig();
            return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTailorProfile(arg0: string): Promise<TailorProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTailorProfile(arg0);
                return from_candid_opt_n58(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTailorProfile(arg0);
            return from_candid_opt_n58(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserCoinBalance(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserCoinBalance();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserCoinBalance();
            return result;
        }
    }
    async getUserProfile(): Promise<UserProfileV2 | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile();
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile();
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfileByPrincipal(arg0: Principal): Promise<UserProfileV2 | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfileByPrincipal(arg0);
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfileByPrincipal(arg0);
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isCallerApproved(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerApproved();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerApproved();
            return result;
        }
    }
    async listApprovals(): Promise<Array<UserApprovalInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.listApprovals();
                return from_candid_vec_n59(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listApprovals();
            return from_candid_vec_n59(this._uploadFile, this._downloadFile, result);
        }
    }
    async placeExtendedOrder(arg0: ExtendedOrder): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.placeExtendedOrder(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.placeExtendedOrder(arg0);
            return result;
        }
    }
    async removeFromCart(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeFromCart(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeFromCart(arg0);
            return result;
        }
    }
    async requestApproval(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.requestApproval();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestApproval();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfileInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async saveTailorProfile(arg0: TailorProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveTailorProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveTailorProfile(arg0);
            return result;
        }
    }
    async saveUserProfile(arg0: UserProfileInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveUserProfile(arg0);
            return result;
        }
    }
    async setApproval(arg0: Principal, arg1: ApprovalStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setApproval(arg0, to_candid_ApprovalStatus_n64(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setApproval(arg0, to_candid_ApprovalStatus_n64(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateExtendedOrderStatus(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateExtendedOrderStatus(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateExtendedOrderStatus(arg0, arg1, arg2);
            return result;
        }
    }
    async updatePlatformConfig(arg0: PlatformConfig): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePlatformConfig(await to_candid_PlatformConfig_n66(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePlatformConfig(await to_candid_PlatformConfig_n66(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateUserRole(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUserRole(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUserRole(arg0);
            return result;
        }
    }
}
async function from_candid_AppStyle_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AppStyle): Promise<AppStyle> {
    return await from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_ApprovalStatus_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApprovalStatus): ApprovalStatus {
    return from_candid_variant_n63(_uploadFile, _downloadFile, value);
}
function from_candid_ButtonStyle_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ButtonStyle): ButtonStyle {
    return from_candid_record_n34(_uploadFile, _downloadFile, value);
}
async function from_candid_Color_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Color): Promise<Color> {
    return await from_candid_record_n49(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
async function from_candid_Fabric_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Fabric): Promise<Fabric> {
    return await from_candid_record_n49(_uploadFile, _downloadFile, value);
}
function from_candid_FontWeight_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FontWeight): FontWeight {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function from_candid_Notification_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Notification): Notification {
    return from_candid_record_n37(_uploadFile, _downloadFile, value);
}
async function from_candid_PlatformConfig_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PlatformConfig): Promise<PlatformConfig> {
    return await from_candid_record_n42(_uploadFile, _downloadFile, value);
}
async function from_candid_Product_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Product): Promise<Product> {
    return await from_candid_record_n55(_uploadFile, _downloadFile, value);
}
function from_candid_Promotion_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Promotion): Promotion {
    return from_candid_record_n45(_uploadFile, _downloadFile, value);
}
function from_candid_TextStyle_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TextStyle): TextStyle {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_UserApprovalInfo_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserApprovalInfo): UserApprovalInfo {
    return from_candid_record_n61(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
async function from_candid_WorkType_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WorkType): Promise<WorkType> {
    return await from_candid_record_n49(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfileV2]): UserProfileV2 | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n31(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExtendedOrder]): ExtendedOrder | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PlatformConfig]): Promise<PlatformConfig | null> {
    return value.length === 0 ? null : await from_candid_PlatformConfig_n41(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TailorProfile]): TailorProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    fonts: {
        body: _TextStyle;
        heading: _TextStyle;
    };
    backgroundImage: [] | [_ExternalBlob];
    colors: _ColorScheme;
    buttons: {
        secondary: _ButtonStyle;
        primary: _ButtonStyle;
    };
}): Promise<{
    fonts: {
        body: TextStyle;
        heading: TextStyle;
    };
    backgroundImage?: ExternalBlob;
    colors: ColorScheme;
    buttons: {
        secondary: ButtonStyle;
        primary: ButtonStyle;
    };
}> {
    return {
        fonts: from_candid_record_n25(_uploadFile, _downloadFile, value.fonts),
        backgroundImage: record_opt_to_undefined(await from_candid_opt_n30(_uploadFile, _downloadFile, value.backgroundImage)),
        colors: value.colors,
        buttons: from_candid_record_n32(_uploadFile, _downloadFile, value.buttons)
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    body: _TextStyle;
    heading: _TextStyle;
}): {
    body: TextStyle;
    heading: TextStyle;
} {
    return {
        body: from_candid_TextStyle_n26(_uploadFile, _downloadFile, value.body),
        heading: from_candid_TextStyle_n26(_uploadFile, _downloadFile, value.heading)
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    weight: _FontWeight;
    font: string;
    color: string;
    size: bigint;
}): {
    weight: FontWeight;
    font: string;
    color: string;
    size: bigint;
} {
    return {
        weight: from_candid_FontWeight_n28(_uploadFile, _downloadFile, value.weight),
        font: value.font,
        color: value.color,
        size: value.size
    };
}
function from_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    secondary: _ButtonStyle;
    primary: _ButtonStyle;
}): {
    secondary: ButtonStyle;
    primary: ButtonStyle;
} {
    return {
        secondary: from_candid_ButtonStyle_n33(_uploadFile, _downloadFile, value.secondary),
        primary: from_candid_ButtonStyle_n33(_uploadFile, _downloadFile, value.primary)
    };
}
function from_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    borderRadius: bigint;
    background: string;
    text: _TextStyle;
    padding: string;
}): {
    borderRadius: bigint;
    background: string;
    text: TextStyle;
    padding: string;
} {
    return {
        borderRadius: value.borderRadius,
        background: value.background,
        text: from_candid_TextStyle_n26(_uploadFile, _downloadFile, value.text),
        padding: value.padding
    };
}
function from_candid_record_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    body: string;
    targetAudience: {
        all: null;
    } | {
        tailors: null;
    } | {
        customers: null;
    };
    timestamp: bigint;
}): {
    id: string;
    title: string;
    body: string;
    targetAudience: Variant_all_tailors_customers;
    timestamp: bigint;
} {
    return {
        id: value.id,
        title: value.title,
        body: value.body,
        targetAudience: from_candid_variant_n38(_uploadFile, _downloadFile, value.targetAudience),
        timestamp: value.timestamp
    };
}
async function from_candid_record_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    promotions: Array<_Promotion>;
    fabrics: Array<_Fabric>;
    banners: Array<_ExternalBlob>;
    cities: Array<_City>;
    colors: Array<_Color>;
    products: Array<_Product>;
    workTypes: Array<_WorkType>;
}): Promise<{
    promotions: Array<Promotion>;
    fabrics: Array<Fabric>;
    banners: Array<ExternalBlob>;
    cities: Array<City>;
    colors: Array<Color>;
    products: Array<Product>;
    workTypes: Array<WorkType>;
}> {
    return {
        promotions: from_candid_vec_n43(_uploadFile, _downloadFile, value.promotions),
        fabrics: await from_candid_vec_n47(_uploadFile, _downloadFile, value.fabrics),
        banners: await from_candid_vec_n50(_uploadFile, _downloadFile, value.banners),
        cities: value.cities,
        colors: await from_candid_vec_n51(_uploadFile, _downloadFile, value.colors),
        products: await from_candid_vec_n53(_uploadFile, _downloadFile, value.products),
        workTypes: await from_candid_vec_n56(_uploadFile, _downloadFile, value.workTypes)
    };
}
function from_candid_record_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    active: boolean;
    discountValue: bigint;
    validFrom: bigint;
    discountType: {
        flat: bigint;
    } | {
        percentage: bigint;
    };
    description: string;
    applicableCategories: Array<string>;
    validUntil: bigint;
}): {
    id: string;
    title: string;
    active: boolean;
    discountValue: bigint;
    validFrom: bigint;
    discountType: {
        __kind__: "flat";
        flat: bigint;
    } | {
        __kind__: "percentage";
        percentage: bigint;
    };
    description: string;
    applicableCategories: Array<string>;
    validUntil: bigint;
} {
    return {
        id: value.id,
        title: value.title,
        active: value.active,
        discountValue: value.discountValue,
        validFrom: value.validFrom,
        discountType: from_candid_variant_n46(_uploadFile, _downloadFile, value.discountType),
        description: value.description,
        applicableCategories: value.applicableCategories,
        validUntil: value.validUntil
    };
}
async function from_candid_record_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    name: string;
    image: [] | [_ExternalBlob];
}): Promise<{
    id: string;
    name: string;
    image?: ExternalBlob;
}> {
    return {
        id: value.id,
        name: value.name,
        image: record_opt_to_undefined(await from_candid_opt_n30(_uploadFile, _downloadFile, value.image))
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
async function from_candid_record_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    isDeleted: boolean;
    tailorId: string;
    customizationOptions: _CustomizationOptions;
    description: string;
    category: string;
    image: _ExternalBlob;
    price: number;
}): Promise<{
    id: string;
    title: string;
    isDeleted: boolean;
    tailorId: string;
    customizationOptions: CustomizationOptions;
    description: string;
    category: string;
    image: ExternalBlob;
    price: number;
}> {
    return {
        id: value.id,
        title: value.title,
        isDeleted: value.isDeleted,
        tailorId: value.tailorId,
        customizationOptions: value.customizationOptions,
        description: value.description,
        category: value.category,
        image: await from_candid_ExternalBlob_n31(_uploadFile, _downloadFile, value.image),
        price: value.price
    };
}
function from_candid_record_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _ApprovalStatus;
    principal: Principal;
}): {
    status: ApprovalStatus;
    principal: Principal;
} {
    return {
        status: from_candid_ApprovalStatus_n62(_uploadFile, _downloadFile, value.status),
        principal: value.principal
    };
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    normal: null;
} | {
    bold: null;
} | {
    light: null;
}): FontWeight {
    return "normal" in value ? FontWeight.normal : "bold" in value ? FontWeight.bold : "light" in value ? FontWeight.light : value;
}
function from_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    all: null;
} | {
    tailors: null;
} | {
    customers: null;
}): Variant_all_tailors_customers {
    return "all" in value ? Variant_all_tailors_customers.all : "tailors" in value ? Variant_all_tailors_customers.tailors : "customers" in value ? Variant_all_tailors_customers.customers : value;
}
function from_candid_variant_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    flat: bigint;
} | {
    percentage: bigint;
}): {
    __kind__: "flat";
    flat: bigint;
} | {
    __kind__: "percentage";
    percentage: bigint;
} {
    return "flat" in value ? {
        __kind__: "flat",
        flat: value.flat
    } : "percentage" in value ? {
        __kind__: "percentage",
        percentage: value.percentage
    } : value;
}
function from_candid_variant_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): ApprovalStatus {
    return "pending" in value ? ApprovalStatus.pending : "approved" in value ? ApprovalStatus.approved : "rejected" in value ? ApprovalStatus.rejected : value;
}
function from_candid_vec_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Notification>): Array<Notification> {
    return value.map((x)=>from_candid_Notification_n36(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Promotion>): Array<Promotion> {
    return value.map((x)=>from_candid_Promotion_n44(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Fabric>): Promise<Array<Fabric>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Fabric_n48(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ExternalBlob>): Promise<Array<ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await from_candid_ExternalBlob_n31(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Color>): Promise<Array<Color>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Color_n52(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Product>): Promise<Array<Product>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Product_n54(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_WorkType>): Promise<Array<WorkType>> {
    return await Promise.all(value.map(async (x)=>await from_candid_WorkType_n57(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserApprovalInfo>): Array<UserApprovalInfo> {
    return value.map((x)=>from_candid_UserApprovalInfo_n60(_uploadFile, _downloadFile, x));
}
function to_candid_ApprovalStatus_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApprovalStatus): _ApprovalStatus {
    return to_candid_variant_n65(_uploadFile, _downloadFile, value);
}
async function to_candid_Color_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Color): Promise<_Color> {
    return await to_candid_record_n9(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
async function to_candid_Fabric_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Fabric): Promise<_Fabric> {
    return await to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid_Notification_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Notification): _Notification {
    return to_candid_record_n18(_uploadFile, _downloadFile, value);
}
async function to_candid_PlatformConfig_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PlatformConfig): Promise<_PlatformConfig> {
    return await to_candid_record_n67(_uploadFile, _downloadFile, value);
}
async function to_candid_Product_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Product): Promise<_Product> {
    return await to_candid_record_n13(_uploadFile, _downloadFile, value);
}
function to_candid_Promotion_n69(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Promotion): _Promotion {
    return to_candid_record_n70(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n16(_uploadFile, _downloadFile, value);
}
async function to_candid_WorkType_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: WorkType): Promise<_WorkType> {
    return await to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
async function to_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    isDeleted: boolean;
    tailorId: string;
    customizationOptions: CustomizationOptions;
    description: string;
    category: string;
    image: ExternalBlob;
    price: number;
}): Promise<{
    id: string;
    title: string;
    isDeleted: boolean;
    tailorId: string;
    customizationOptions: _CustomizationOptions;
    description: string;
    category: string;
    image: _ExternalBlob;
    price: number;
}> {
    return {
        id: value.id,
        title: value.title,
        isDeleted: value.isDeleted,
        tailorId: value.tailorId,
        customizationOptions: value.customizationOptions,
        description: value.description,
        category: value.category,
        image: await to_candid_ExternalBlob_n10(_uploadFile, _downloadFile, value.image),
        price: value.price
    };
}
function to_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    body: string;
    targetAudience: Variant_all_tailors_customers;
    timestamp: bigint;
}): {
    id: string;
    title: string;
    body: string;
    targetAudience: {
        all: null;
    } | {
        tailors: null;
    } | {
        customers: null;
    };
    timestamp: bigint;
} {
    return {
        id: value.id,
        title: value.title,
        body: value.body,
        targetAudience: to_candid_variant_n19(_uploadFile, _downloadFile, value.targetAudience),
        timestamp: value.timestamp
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
async function to_candid_record_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    promotions: Array<Promotion>;
    fabrics: Array<Fabric>;
    banners: Array<ExternalBlob>;
    cities: Array<City>;
    colors: Array<Color>;
    products: Array<Product>;
    workTypes: Array<WorkType>;
}): Promise<{
    promotions: Array<_Promotion>;
    fabrics: Array<_Fabric>;
    banners: Array<_ExternalBlob>;
    cities: Array<_City>;
    colors: Array<_Color>;
    products: Array<_Product>;
    workTypes: Array<_WorkType>;
}> {
    return {
        promotions: to_candid_vec_n68(_uploadFile, _downloadFile, value.promotions),
        fabrics: await to_candid_vec_n72(_uploadFile, _downloadFile, value.fabrics),
        banners: await to_candid_vec_n73(_uploadFile, _downloadFile, value.banners),
        cities: value.cities,
        colors: await to_candid_vec_n74(_uploadFile, _downloadFile, value.colors),
        products: await to_candid_vec_n75(_uploadFile, _downloadFile, value.products),
        workTypes: await to_candid_vec_n76(_uploadFile, _downloadFile, value.workTypes)
    };
}
function to_candid_record_n70(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    active: boolean;
    discountValue: bigint;
    validFrom: bigint;
    discountType: {
        __kind__: "flat";
        flat: bigint;
    } | {
        __kind__: "percentage";
        percentage: bigint;
    };
    description: string;
    applicableCategories: Array<string>;
    validUntil: bigint;
}): {
    id: string;
    title: string;
    active: boolean;
    discountValue: bigint;
    validFrom: bigint;
    discountType: {
        flat: bigint;
    } | {
        percentage: bigint;
    };
    description: string;
    applicableCategories: Array<string>;
    validUntil: bigint;
} {
    return {
        id: value.id,
        title: value.title,
        active: value.active,
        discountValue: value.discountValue,
        validFrom: value.validFrom,
        discountType: to_candid_variant_n71(_uploadFile, _downloadFile, value.discountType),
        description: value.description,
        applicableCategories: value.applicableCategories,
        validUntil: value.validUntil
    };
}
async function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    name: string;
    image?: ExternalBlob;
}): Promise<{
    id: string;
    name: string;
    image: [] | [_ExternalBlob];
}> {
    return {
        id: value.id,
        name: value.name,
        image: value.image ? candid_some(await to_candid_ExternalBlob_n10(_uploadFile, _downloadFile, value.image)) : candid_none()
    };
}
function to_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_all_tailors_customers): {
    all: null;
} | {
    tailors: null;
} | {
    customers: null;
} {
    return value == Variant_all_tailors_customers.all ? {
        all: null
    } : value == Variant_all_tailors_customers.tailors ? {
        tailors: null
    } : value == Variant_all_tailors_customers.customers ? {
        customers: null
    } : value;
}
function to_candid_variant_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApprovalStatus): {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
} {
    return value == ApprovalStatus.pending ? {
        pending: null
    } : value == ApprovalStatus.approved ? {
        approved: null
    } : value == ApprovalStatus.rejected ? {
        rejected: null
    } : value;
}
function to_candid_variant_n71(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "flat";
    flat: bigint;
} | {
    __kind__: "percentage";
    percentage: bigint;
}): {
    flat: bigint;
} | {
    percentage: bigint;
} {
    return value.__kind__ === "flat" ? {
        flat: value.flat
    } : value.__kind__ === "percentage" ? {
        percentage: value.percentage
    } : value;
}
function to_candid_vec_n68(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Promotion>): Array<_Promotion> {
    return value.map((x)=>to_candid_Promotion_n69(_uploadFile, _downloadFile, x));
}
async function to_candid_vec_n72(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Fabric>): Promise<Array<_Fabric>> {
    return await Promise.all(value.map(async (x)=>await to_candid_Fabric_n11(_uploadFile, _downloadFile, x)));
}
async function to_candid_vec_n73(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<ExternalBlob>): Promise<Array<_ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await to_candid_ExternalBlob_n10(_uploadFile, _downloadFile, x)));
}
async function to_candid_vec_n74(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Color>): Promise<Array<_Color>> {
    return await Promise.all(value.map(async (x)=>await to_candid_Color_n8(_uploadFile, _downloadFile, x)));
}
async function to_candid_vec_n75(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Product>): Promise<Array<_Product>> {
    return await Promise.all(value.map(async (x)=>await to_candid_Product_n12(_uploadFile, _downloadFile, x)));
}
async function to_candid_vec_n76(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<WorkType>): Promise<Array<_WorkType>> {
    return await Promise.all(value.map(async (x)=>await to_candid_WorkType_n14(_uploadFile, _downloadFile, x)));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
